---
# tasks file for kube-node
- name: Installing docker
  package:
          name: docker
          state: present

- name: Start docker service
  service:
          name: docker
          state: started
          enabled: yes

- name: Kubernetes repo alternate
  copy:
          src: kubernetes.repo
          dest: /etc/yum.repos.d/kubernetes.repo


- name: Installing softwares
  yum:
          name: "{{ item }}"
          state: present
          disable_excludes: kubernetes
  loop:
          - kubectl
          - kubeadm
          - kubelet

- name: Start and enable kubelet services
  service:
          name: kubelet
          state: started
          enabled: yes

- name: pull config images
  command: "kubeadm config images pull"


- name: change docker configuration
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json


- name: restart docker
  service:
          name: docker
          state: restarted

- name: Install ip-route tc
  package:
          name: iproute-tc
          state: present

- name: make routing policy
  copy:
          src: k8s.conf
          dest: /etc/sysctl.d/k8s.conf

- name: enable system
  shell: "sysctl --system"

- name: free some RAM caches
  shell: "echo 3 > /proc/sys/vm/drop_caches"

- name: "Copy token to slave"
  copy:
          src: /tmp/token
          dest: /tmp/token

- name: "Join node to cluster"
  shell: "bash /tmp/token"
  ignore_errors: True
